server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否将eureka自身作为应用注册到焐热卡注册中心
    fetch-registry: false
  server:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/